SweetChef/SweetChef/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SweetChef.Models;
using SweetChef.ModelsNew;

namespace SweetChef.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly SweetContext _context;

        public HomeController(SweetContext context)
        {
            _context = context;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                return Redirect("/Home/Cozinhar/");
            }

            return View();
        }


        public IActionResult Cozinhar()
        {
            ViewData["NomeUtilizador"] = GetNomeUtilizador();
            return View();
        }

        public IActionResult Configuracao()
        {
            ViewData["NomeUtilizador"] = GetNomeUtilizador();

            return View();
        }
        public IActionResult Insercao()
        {
            return View();
        }

        public IActionResult Editor(int id)
        {
            ViewData["NomeUtilizador"] = GetNomeUtilizador();
            if (_context.Receita.Find(id) != null)
                ViewData["ReceitaId"] = id;
            else
                ViewData["ReceitaId"] = "Unknown";

            return View();
        }

        public IActionResult Tutorial()
        {
            ViewData["NomeUtilizador"] = GetNomeUtilizador();

            return View();
        }

       
        public IActionResult EmentaSemanal()
        {
            var sidut = HttpContext.User.Identity.Name;
            int idUt = Int32.Parse(sidut);
            ViewData["idUser"] = idUt;
            ViewData["NomeUtilizador"] = GetNomeUtilizador();

            return View();
        }

        public IActionResult SobreCozinhados()
        {
            ViewData["NomeUtilizador"] = GetNomeUtilizador();

            return View();
        }

        public IActionResult Privacidade()
        {
            ViewData["NomeUtilizador"] = GetNomeUtilizador();

            return View();
        }

        public IActionResult ListaCompras()
        {
            ViewData["NomeUtilizador"] = GetNomeUtilizador();

            return View();
        }

        public IActionResult Receita(int id)
        {
            Receita receita = _context.Find<Receita>(id);
            if (receita == null)
            {
                return NotFound();
            }
            ViewData["ReceitaId"] = id;
            ViewData["ReceitaNome"] = receita.Nome;
            ViewData["NomeUtilizador"] = GetNomeUtilizador();

            return View();
        }

        public IActionResult Ingrediente(int id)
        {
            Ingrediente ingrediente = _context.Find<Ingrediente>(id);
            if (ingrediente == null)
            {
                return NotFound();
            }
            ViewData["Id"] = id;
            ViewData["Nome"] = ingrediente.Nome;
            ViewData["Img"] = ingrediente.ImageLink;
            ViewData["NomeUtilizador"] = GetNomeUtilizador();

            return View();
        }

        public IActionResult Utensilio(int id)
        {
            Utensilio utensilio = _context.Find<Utensilio>(id);
            if (utensilio == null)
            {
                return NotFound();
            }
            ViewData["Id"] = id;
            ViewData["Nome"] = utensilio.Nome;
            ViewData["Img"] = utensilio.ImageLink;
            ViewData["NomeUtilizador"] = GetNomeUtilizador();

            return View();
        }

        public IActionResult PassoAPasso(int id, [FromQuery] bool? ultimoPasso, [FromQuery] int tempo)
        {
            Receita receita = _context.Find<Receita>(id);
            if(receita == null)
            {
                return NotFound();
            }
            ViewData["ReceitaId"] = id;
            ViewData["ReceitaNome"] = receita.Nome;
            ViewData["UltimoPasso"] = ultimoPasso;
            ViewData["tempo"] = tempo;
            ViewData["NomeUtilizador"] = GetNomeUtilizador();

            return View();
        }

        public IActionResult Feedback(int id, [FromQuery] int tempo, [FromQuery] DateTime data)
        {
            Receita receita = _context.Find<Receita>(id);
            if (receita == null)
            {
                return NotFound();
            }
            ViewData["ReceitaId"] = id;
            ViewData["ReceitaNome"] = receita.Nome;
            ViewData["ReceitaDuracao"] = receita.Tempodepreparacao;
            ViewData["tempo"] = tempo / 60000;
            ViewData["data"] = data;
            ViewData["NomeUtilizador"] = GetNomeUtilizador();

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            ViewData["NomeUtilizador"] = GetNomeUtilizador();

            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private String GetNomeUtilizador()
        {
            var sidut = ControllerContext.HttpContext.User.Identity.Name;
            int idUt = Int32.Parse(sidut);
            string ut = _context.Utilizador.Where(p => p.Id == idUt).Select(u => u.Nome).FirstOrDefault();
            if (ut == null)
                return "";
            return ut;
        }
    }
}

SweetChef/SweetChef/Controllers/IngredienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SweetChef.ModelsNew;

namespace SweetChef.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    [Authorize]
    public class IngredienteController : ControllerBase
    {
        private readonly SweetContext _context;

        public IngredienteController(SweetContext context)
        {
            _context = context;
        }

        [HttpGet]
        public ActionResult Ingredientes()
        {
            var t = _context.Ingrediente.Include(i => i.Unidade).ToArray();
            if (t.Length == 0)
                return Ok("[]");
            return Ok(t);
        }

        [HttpPost]
        public ActionResult PostIngrediente([FromForm]Ingrediente ing)
        {
            _context.Ingrediente.Add(ing);
            _context.SaveChanges();
            return Redirect(Request.Host.Value);
        }

        [HttpPut]
        public ActionResult UpdateIngrediente([FromForm]Ingrediente ing)
        {
            _context.Ingrediente.Update(ing);
            _context.SaveChanges();
            return Ok();
        }

        [HttpGet("unidade")]
        public ActionResult GetUnidade()
        {
            return Ok(_context.Unidade.ToArray());
        }

        [HttpPost("unidade")]
        public ActionResult PostUnidade([FromForm]Unidade un)
        {
            _context.Unidade.Add(un);
            _context.SaveChanges();
            return Ok();
        }
    }
}

SweetChef/SweetChef/Controllers/UtilizadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Web.Http;
using SweetChef.ModelsNew;
using Microsoft.EntityFrameworkCore;
using GeoCoordinatePortable;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;


namespace SweetChef.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    [Authorize]
    public class UtilizadorController : ControllerBase
    {
        //private readonly UtilizadorContext _contexts;
        private readonly SweetContext _context;

        // TODO: Corrigir erro
        
        public UtilizadorController(SweetContext context)
        {
            _context = context;
        }

        //Get receitas favoritas
        [HttpGet("favoritas")]
        public ActionResult getReceitasFavoritas()
        {
            try
            {
                var sidut = ControllerContext.HttpContext.User.Identity.Name;
                int idUt = Int32.Parse(sidut);
                var utilizador = _context.Utilizador.
                                                Include("Opiniao.Receita").
                                                Where(p => p.Id == idUt).
                                                FirstOrDefault();
                                                
                if (utilizador == null)
                {
                    return NotFound();
                }

                var receitas = utilizador.Opiniao
                               .Where(o => o.Favorito == true)
                               .Select(o => o.Receita)
                               .ToArray();
                return Ok(receitas);
            }
            catch (Exception e)
            {
                System.Diagnostics.Debug.Print(e.ToString());
                return StatusCode(StatusCodes.Status500InternalServerError);
            }
        }
        //Create Execução
        [HttpPost("execucao")]
        public ActionResult PostExecucao([FromForm] int idReceita, [FromForm] DateTime data, [FromForm] int duracao)
        {
            try
            {
                var sidut = ControllerContext.HttpContext.User.Identity.Name;
                int idUt = Int32.Parse(sidut);
                Execucao e = _context.Execucao.Find(idUt, idReceita, data);
                if (e != null)
                {
                    return Created("Object Already Exists", null);
                }
                e = new Execucao();
                e.Utilizadorid = idUt;
                e.Receitaid = idReceita;
                e.Data = data;
                e.DuracaoTotal = duracao;
                _context.Execucao.Add(e);
                _context.SaveChanges();
                return Ok();
            }
            catch (Exception e)
            {
                System.Diagnostics.Debug.Print(e.ToString());
                return StatusCode(StatusCodes.Status500InternalServerError);
            }
        }

        //Vai buscar as ementas semanais de uma certa data
        [HttpGet("ementa")]
        public ActionResult GetReceitasEmenta([FromQuery] DateTime dataInicial, [FromQuery] DateTime dataFinal)
        {
           
            try
            {
                var sidut = ControllerContext.HttpContext.User.Identity.Name;
                int idUt = Int32.Parse(sidut);
                var ementa= _context.EmentaSemanal.
                   Where(em => em.Utilizadorid == idUt && em.Data >= dataInicial && em.Data <= dataFinal).
                   Select(em => new { em.Receita, em.Data}).
                   ToList();
                ementa.Sort((e1, e2) => e1.Data.CompareTo(e2.Data));
                return Ok(ementa);
            }
            catch (Exception e)
            {
                System.Diagnostics.Debug.Print(e.ToString());
                return StatusCode(StatusCodes.Status500InternalServerError);
            }
        }
     
        //Adiciona uma receita à ementa
        [HttpPost("ementa")]
        public ActionResult PostReceitaEmenta([FromForm] int idRec, [FromForm] DateTime data)
        {
            try
            {
                var sidut = ControllerContext.HttpContext.User.Identity.Name;
                int idUt = Int32.Parse(sidut);
                EmentaSemanal em = _context.EmentaSemanal.Find(data, idRec, idUt);
                if(em != null)
                {
                    return Created("Object Already Exists", null);
                }
                em = new EmentaSemanal();
                em.Utilizadorid = idUt;
                em.Receitaid = idRec;
                em.Data = data;
                _context.EmentaSemanal.Add(em);
                _context.SaveChanges();
                return Ok();
            }
            catch (Exception e)
            {
                System.Diagnostics.Debug.Print(e.ToString());
                return StatusCode(StatusCodes.Status500InternalServerError);
            }
        }

        //Remove uma receita da ementa
        [HttpDelete("ementa")]
        public IActionResult Delete([FromQuery] int idRec, [FromQuery] DateTime data)
        {
            try
            {
                var sidut = ControllerContext.HttpContext.User.Identity.Name;
                int idUt = Int32.Parse(sidut);
                //TODO ver se a ordem está correta 
                var ementa = _context.EmentaSemanal.Find(data, idRec, idUt);

                if (ementa == null)
                {
                    return NotFound();
                }
                _context.EmentaSemanal.Remove(ementa);
                _context.SaveChanges();
                return NoContent();
            }
            catch (Exception e)
            {
                System.Diagnostics.Debug.Print(e.ToString());
                return StatusCode(StatusCodes.Status500InternalServerError);
            }
        }


       
        //Basicamente se não me passa a lista quer dizer que não quer cenas
        [HttpPost("configuracao/preferida")]
        public ActionResult AddConfiguracaoPreferida([FromQuery] int preferida)
        {
            try
            {
                var sidut = ControllerContext.HttpContext.User.Identity.Name;
                int idUt = Int32.Parse(sidut);
                Likes l = new Likes();
                l.Utilizadorid = idUt;
                l.Tagid = preferida;
                _context.Likes.Add(l);
                _context.SaveChanges();
                return Ok(l);
             }
            catch (Exception e)
            {
                System.Diagnostics.Debug.Print(e.ToString());
                return StatusCode(StatusCodes.Status500InternalServerError);
            }
        }

        [HttpGet("configuracao/preferidas")]
        public ActionResult GetConfiguracaoPreferidas()
        {
            try
            {
                var sidut = ControllerContext.HttpContext.User.Identity.Name;
                int idUt = Int32.Parse(sidut);
                var likes = _context.Likes.Where(x => x.Utilizadorid == idUt).ToList();
                
                return Ok(likes);
            }
            catch (Exception e)
            {
                System.Diagnostics.Debug.Print(e.ToString());
                return StatusCode(StatusCodes.Status500InternalServerError);
            }
        }

        [HttpDelete("configuracao/preferida")]
        public ActionResult RemoveConfiguracaoPreferida([FromQuery] int preferida)
        {
            try
            {
                var sidut = ControllerContext.HttpContext.User.Identity.Name;
                int idUt = Int32.Parse(sidut);
                Likes l = _context.Likes.Find(idUt, preferida);
                if(l == null)
                {
                    return NotFound(preferida);
                }
                else
                {
                    _context.Likes.Remove(l);
                    _context.SaveChanges();
                    return Ok(l);
                }    
            }
            catch (Exception e)
            {
                System.Diagnostics.Debug.Print(e.ToString());
                return StatusCode(StatusCodes.Status500InternalServerError);
            }
        }
        [HttpPost("configuracao/restricao")]
        public ActionResult UpdateConfiguracaoPreferidas([FromQuery] int restricao)
        {
            try
            {
                var sidut = ControllerContext.HttpContext.User.Identity.Name;
                int idUt = Int32.Parse(sidut);
                RestricoesAlimentares r = new RestricoesAlimentares();
                r.Utilizadorid = idUt;
                r.Ingredienteid = restricao;
                _context.RestricoesAlimentares.Add(r);
                _context.SaveChanges();
                return Ok(r);
            }
            catch (Exception e)
            {
                System.Diagnostics.Debug.Print(e.ToString());
                return StatusCode(StatusCodes.Status500InternalServerError);
            }
        }

        [HttpGet("configuracao/restricoes")]
        public ActionResult GetConfiguracaoRestricoes()
        {
            try
            {
                var sidut = ControllerContext.HttpContext.User.Identity.Name;
                int idUt = Int32.Parse(sidut);
                var restricoes = _context.RestricoesAlimentares.Where(x => x.Utilizadorid == idUt).ToList();

                return Ok(restricoes);
            }
            catch (Exception e)
            {
                System.Diagnostics.Debug.Print(e.ToString());
                return StatusCode(StatusCodes.Status500InternalServerError);
            }
        }

        [HttpDelete("configuracao/restricao")]
        public ActionResult RemoveConfiguracaoExcluidas([FromQuery] int restricao)
        {
            try
            {

SweetChef/SweetChef/Views/Home/Configuracao.cshtml
@{
    ViewData["Title"] = "Definições de utilizador";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<script>
    // api/utilizador/configuracao/preferida excluido restricao

    // etiquetas
    $(function () {
        $.getJSON("/api/Tag", (data) => {
            for (const etiqueta of data) {

                let element = $($("#checkboxTemplate").html());
                element.find(".textTemplate").text(etiqueta.nome);
                element.find(".checkTemplate").addClass("preferidaCheck");
                element.find(".checkTemplate").attr("id", "etiquetaPref" + etiqueta.id);
                element.find(".labelTemplate").attr("for", "etiquetaPref" + etiqueta.id);
                element.appendTo("#etiquetasMenuPref");

                element = $($("#checkboxTemplate").html());
                element.find(".textTemplate").text(etiqueta.nome);
                element.find(".checkTemplate").addClass("excluidaCheck");
                element.find(".checkTemplate").attr("id", "etiquetaExcl" + etiqueta.id);
                element.find(".labelTemplate").attr("for", "etiquetaExcl" + etiqueta.id);
                element.appendTo("#etiquetasMenuExc");
            }

            $.getJSON("/api/utilizador/configuracao/preferidas", (data) => {
                for (const { tagid } of data) {
                    $("#etiquetaPref" + tagid).prop("checked", true);
                }
            });

            $.getJSON("/api/utilizador/configuracao/excluidas", (data) => {
                for (const { tagid } of data) {
                    $("#etiquetaExcl" + tagid).prop("checked", true);
                }
            });

            $(".preferidaCheck").on("change", function () {
                let id = Number($(this).attr("id").slice(12));
                if ($(this).prop("checked")) {
                    $.ajax({
                        url: "/api/utilizador/configuracao/preferida?preferida=" + id,
                        type: 'POST',
                        fail: function () {
                            $(this).prop("checked", false);
                        }
                    });
                } else {
                    $.ajax({
                        url: "/api/utilizador/configuracao/preferida?preferida=" + id,
                        type: 'DELETE',
                        fail: function () {
                            $(this).prop("checked", true);
                        }
                    });
                }
            });

            $(".excluidaCheck").on("change", function () {
                let id = Number($(this).attr("id").slice(12));
                if ($(this).prop("checked")) {
                    $.ajax({
                        url: "/api/utilizador/configuracao/excluida?excluido=" + id,
                        type: 'POST',
                        fail: function () {
                            $(this).prop("checked", false);
                        }
                    });
                } else {
                    $.ajax({
                        url: "/api/utilizador/configuracao/excluida?excluido=" + id,
                        type: 'DELETE',
                        fail: function () {
                            $(this).prop("checked", true);
                        }
                    });
                }
            });
        });

        $.getJSON("/api/ingrediente", (data) => {
            for (const ingrediente of data) {

                let element = $($("#checkboxTemplate").html());
                window.ingrediente = element;
                element.find(".textTemplate").text(ingrediente.nome);
                element.find(".checkTemplate").attr("id", "ingrediente" + ingrediente.id);
                element.find(".checkTemplate").addClass("ingrediente");
                element.find(".labelTemplate").attr("for", "ingrediente" + ingrediente.id);
                element.appendTo("#ingredientesMenu");
            }

            $.getJSON("/api/Utilizador/configuracao/restricoes", (data) => {
                for (const { ingredienteid } of data) {
                    $("#ingrediente" + ingredienteid).prop("checked", true);
                }
            });

            $(".ingrediente").on("change", function () {
                let id = Number($(this).attr("id").slice(11));
                if ($(this).prop("checked")) {
                    $.ajax({
                        url: "/api/utilizador/configuracao/restricao?restricao=" + id,
                        type: 'POST',
                        fail: function () {
                            $(this).prop("checked", false);
                        }
                    });
                } else {
                    $.ajax({
                        url: "/api/utilizador/configuracao/restricao?restricao=" + id,
                        type: 'DELETE',
                        fail: function () {
                            $(this).prop("checked", true);
                        }
                    });
                }
            });
        });
    });
</script>

<h4>Preferências da página inicial</h4>
<div class="container">

    <!-- template -->
    <template id="checkboxTemplate">
        <div class="form-check">
            <input class="form-check-input checkTemplate" type="checkbox" value="">
            <label class="form-check-label labelTemplate">
                <span class="textTemplate"></span>
            </label>
        </div>
    </template>

    <div class="row">
        <div class="col">
            <h6>Etiquetas preferidas:</h6>
            <div style="height:7em" class="overflow-auto border p-1" id="etiquetasMenuPref">
                <!-- preenchido com template -->
            </div>
        </div>
        <div class="col">
            <h6>Etiquetas excluidas:</h6>
            <div style="height:7em" class="overflow-auto border p-1" id="etiquetasMenuExc">
                <!-- preenchido com template -->
            </div>
        </div>
        <div class="col">
            <h6>Ingredientes excluídos:</h6>
            <div style="height:7em" class="overflow-auto border p-1" id="ingredientesMenu">
                <!-- preenchido com template -->
            </div>
        </div>
    </div>

</div>

<hr/>



<h4>Ajuda</h4>
<div class="container">
    <a asp-area="" asp-controller="Home" asp-action="Tutorial" class="btn btn-primary mt-3">Tutorial</a>
</div>

<hr />

<a asp-area="" asp-controller="Utilizador" asp-action="logoutAsync" class="btn btn-danger mt-3">Terminar Sessão</a>

SweetChef/SweetChef/Views/Home/Feedback.cshtml
@{
    ViewData["Title"] = ViewData["ReceitaNome"];
}
<h2>@ViewData["ReceitaNome"]</h2>
<script>
    $(function () {
        $.getJSON("/api/Utilizador/opiniao/@ViewData["ReceitaId"]", (data) => {
            $("[name=rating]").val(data.rating);
            $("[name=favorito]").prop("checked", data.favorito);
        });
        $("#feedbackForm").on("submit", function () {
            $.post("/api/Utilizador/execucao", $("#execucaoForm").serialize(), () => {
                $.ajax({
                    url: "/api/Utilizador/opiniao/@ViewData["ReceitaId"]",
                    method: "PUT",
                    data: $("#feedbackForm").serialize()
                }).then(() => {
                    location.href = "@Url.Action("Cozinhar", "Home")";
                });
            });
            return false;
        });
    });
</script>
<p>Duração esperada: @ViewData["ReceitaDuracao"] min</p>
<p>Duração efetiva: @ViewData["tempo"] min</p>
<a class="btn btn-danger my-2 text-white" id="voltar" href="@Url.Action("PassoAPasso","Home", new { id = ViewData["ReceitaId"], ultimoPasso = true, tempo = ViewData["tempo"], data = ViewData["data"]})"><i class='fas fa-arrow-left'></i> Voltar</a>
<form id="execucaoForm">
    <input hidden="hidden" name="idReceita" value="@ViewData["ReceitaId"]"/>
    <input type="hidden" name="data" value="@ViewData["data"]"/>
    <input type="hidden" name="duracao" value="@ViewData["tempo"]"/>
</form>
<div class="form-group row">
    <label class="col-sm-2 col-form-label">
        Qualidade do sabor do cozinhado
    </label>
    1<input class="col-sm-2" type="range" max="5" min="1">5
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label">
        Qualidade visual do cozinhado
    </label>
    1<input class="col-sm-2" type="range" max="5" min="1">5
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label">
        Dificuldade na confeção
    </label>
    1<input class="col-sm-2" type="range" max="5" min="1">5
</div>
<form id="feedbackForm">
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" for="rating">
            Avaliação
        </label>
        <input class="col-sm-2" type="number" name="rating" id="rating" max="5" min="1">
    </div>
    <div class="form-check">
        <input class="form-check-input" type="checkbox" name="favorito" id="favorito" value="True">
        <label class="form-check-label" for="favorito">
            Adicionar aos favoritos
        </label>
    </div>
    <div class="form-group mt-2">
        <input class="btn btn-primary" type="submit" value="Guardar">
    </div>
</form>

SweetChef/SweetChef/Views/Home/Index.cshtml
@{
    //ViewData["Title"] = "Home Page";
}
<style>
    .container {
        background-color: transparent !important;
        height: 100% !important;
        margin-top: 0 !important;
        margin-bottom: -57px !important;
    }

    body {
        height: 100vh !important;
    }
</style>

<div class="row justify-content-center align-items-center h-100" id="entrar">
    <div class="col-md-4 bg-light p-3 rounded">
        <h1>Entrar</h1>
        <form method="post" action="/api/utilizador/autenticar">
            <div class="form-group">
                <label for="emailLogin">E-mail</label>
                <input type="email" required name="email" class="form-control" id="emailLogin" placeholder="Introduza e-mail">
            </div>
            <div class="form-group">
                <label for="passwordLogin">Password</label>
                <input type="password" minlength="6" required autocomplete="current-password" name="password" class="form-control" id="passwordLogin" placeholder="Password">
            </div>
            <div class="form-group">
                <a href="#registar">Não tem conta?</a>
            </div>
            <button type="submit" class="btn btn-primary">Entrar</button>
        </form>
    </div>
</div>


<div class="row justify-content-center align-items-center h-100 d-none" id="registar">
    <div class="col-md-4 bg-light p-3 rounded">
        <h1>Registar</h1>
        <form method="post" action="/api/utilizador/registar">
            <div class="form-group">
                <label for="nomeRegisto">Nome</label>
                <input type="text" maxlength="60" required name="nome" autocomplete="name" class="form-control" id="nomeRegisto" placeholder="Introduza o seu nome">
            </div>
            <div class="form-group">
                <label for="emailRegisto">E-mail</label>
                <input type="email" required name="email" class="form-control" id="emailRegisto" placeholder="Introduza o seu e-mail">
            </div>
            <div class="form-group">
                <label for="dataNascimentoRegisto">Data de nascimento</label>
                <script>
                    $(() => $("#dataNascimentoRegisto").attr("max", new Date().toISOString().split("T")[0]));
                </script>
                <input type="date" required name="dataNascimento" class="form-control" id="dataNascimentoRegisto" placeholder="Introduza o seu e-mail">
            </div>
            <div class="form-group">
                <label for="passwordRegisto">Password</label>
                <input type="password" minlength="6" required name="password" class="form-control" id="passwordRegisto" placeholder="Password">
            </div>
            <div class="form-group">
                <a href="#entrar">Já tem conta?</a>
            </div>
            <button type="submit" class="btn btn-primary">Registar</button>
        </form>
    </div>
</div>

<noscript>
    <style>
        #registar {
            display: flex !important;
            margin-bottom: 50px;
        }
    </style>
</noscript>

<script>
    $(window).on('load hashchange', (e) => {
        if (location.hash == "#registar") {
            $("#registar").removeClass("d-none");
            $("#entrar").addClass("d-none")
        } else if (location.hash == "#entrar") {
            $("#entrar").removeClass("d-none");
            $("#registar").addClass("d-none");
        }
    });
</script>

SweetChef/SweetChef/Views/Home/Ingrediente.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Nome"] - SweetChef</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    </environment>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
</head>
<body class="container-fluid">
    <a class="btn btn-primary mb-2" href="https://www.continente.pt/pt-pt/public/Pages/searchresults.aspx?k=@ViewData["Nome"]" target="_blank">Encomendar</a>
    <div class="row">
        <div class="col-lg-4">
            @if (ViewData["Img"] != null) {
                <img class="img-fluid" src="@(ViewData["Img"])" onerror="this.style.display = 'none'" />
            }
        </div>
        <div class="col-lg-8">
            <h3>Onde posso comprar?</h3>
            <iframe src="~/map.html" class="embed-responsive" style="height: 75vh" frameborder="0"></iframe>
        </div>
    </div>
</body>
</html>